### PR TITLE
Fix/remove unused hof form wizard

### PR DESCRIPTION
**Pull request by sulthan-ahmed**
and remove package-lock.json

### CODE REVIEW

**Comment by lennym** [comment]
That's going to make this fail: https://github.com/UKHomeOffice/so-acceptance/blob/master/steps.js#L4

**Comment by sulthan-ahmed** [comment]
so it is using hof-form-wizard afterall so is this PR redundant then?

**Comment by sulthan-ahmed** [comment]
My bad it is being used, note to self, from Lenny, next time use `npx proon` to check if a module is unused

**Comment by lennym** [comment]
Alternatively you can type the name of the module in the search box in github.

**Comment by sulthan-ahmed** [comment]
👍

**Pull request closed without merging**
